#include <compiler/nodes/root.hpp>
#include <compiler/nodes/main.hpp>
#include <compiler/nodes/module.hpp>

#include <compiler/nodes/include.hpp>
#include <compiler/nodes/expression_statement.hpp>
#include <compiler/nodes/while_statement.hpp>
#include <compiler/nodes/loop_statement.hpp>
#include <compiler/nodes/function_statement.hpp>
#include <compiler/nodes/procedure_statement.hpp>
#include <compiler/nodes/variable_statement.hpp>
#include <compiler/nodes/scope_statement.hpp>
#include <compiler/nodes/write_statement.hpp>
#include <compiler/nodes/read_statement.hpp>
#include <compiler/nodes/if_statement.hpp>
#include <compiler/nodes/conditional.hpp>

#include <compiler/nodes/expression.hpp>
#include <compiler/nodes/procedure_call.hpp>
#include <compiler/nodes/assignment.hpp>
#include <compiler/nodes/equality.hpp>
#include <compiler/nodes/comparison.hpp>
#include <compiler/nodes/term.hpp>
#include <compiler/nodes/factor.hpp>
#include <compiler/nodes/magnitude.hpp>
#include <compiler/nodes/extraction.hpp>
#include <compiler/nodes/derivation.hpp>
#include <compiler/nodes/unary.hpp>
#include <compiler/nodes/function_call.hpp>
#include <compiler/nodes/array_index.hpp>
#include <compiler/nodes/primary.hpp>
#include <compiler/nodes/grouping.hpp>
